name: 72BumblebeeLane
favicon: null
layout_spectrum: 0.7222599002998322
typography_spectrum: 0.8929649882484227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26d700'
    - '#ffffff'
    - '#282d2e'
    - '#aeb2b1'
    - '#6b706f'
  brandStrength: 0.2520514044445008
  lightness: 0.8613842050544918
  saturation: 0.9555668064858764
  rhythmicContrast: 0.3051005944143981
purpose: []
